name: Checks

on: [push, pull_request]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install dependencies from yarn.lock
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      # Run linting with yarn
      - run: yarn lint

  static-compat:
    name: Static Compatability
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install dependencies from yarn.lock
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - run: yarn build && yarn export
        env:
          WORDPRESS_GRAPHQL_ENDPOINT: ${{ secrets.WORDPRESS_GRAPHQL_ENDPOINT }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: asifmoh/shongshoy.org
          brach: gh-pages
          folder: out # The folder the action should deploy.  
